#!/usr/bin/env bash

useradd -m -u 1001 sail
usermod -a -G root,www-data sail

mkdir -p /home/sail/.composer && \
chown -R sail:sail /home/sail

if [ $# -gt 0 ];then
    exec gosu 1001 "$@"
else
    /usr/local/bin/php /var/www/html/artisan serve --host=0.0.0.0 --port=80
fi
